version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: plp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: plp_edtech_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: plp-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: plp_edtech_db
    ports:
      - "3000:8080"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: