version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: plp-backend-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      - ../uploads:/usr/src/app/uploads
    networks:
      - plp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data_prod:

networks:
  plp-network:
    driver: bridge